### PR TITLE
Grid components - what I missed before

### PR DESCRIPTION
**Pull request by brumik**

### CODE REVIEW

**Comment by h-kataria** [comment]
@brum does the screen look different visually with these changes?

**Comment by brumik** [comment]
@h-kataria as far as I know, there are no visual changes

**Review by knightsean00 — APPROVED** [review]
This looks great! We might want to consider making a different breakpoint for small devices (`sm={12}`), but I don't think this is super urgent because most users will not be viewing these pages on a mobile device anyway.

**Review by h-kataria — APPROVED** [review]
great work!

**Pull request merged**
