### PR TITLE
Use Reports API to load list and detail reports

### PR DESCRIPTION
**Pull request by h-kataria**
Depends on https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/375

### CODE REVIEW

**Comment by skochay330** [comment]
Code looks fine, but here are some issues I found in the UI: 

1. When templates explorer report preview is selected and I try to use the back arrow to see the previous report, page breaks or jumps to first report in list (onboarding report).
2. All report previews have a flickering behavior (loading the previous report chart again before loading the current one)
3. Templates explorer report is missing expanded rows
4. Host anomalies report is missing 
5. Some tags are missing on the report cards

**Review by skochay330 — CHANGES_REQUESTED** [review]
Code looks fine, but here are some issues I found in the UI:

1. When templates explorer report preview is selected and I try to use the back arrow to see the previous report, page breaks or jumps to first report in list (onboarding report).
2. All report previews have a flickering behavior (loading the previous report chart again before loading the current one)
3. Templates explorer report is missing expanded rows
4. Host anomalies report is missing
5. Some tags are missing on the report cards

**Review by skochay330 — APPROVED** [review]
@h-kataria changes look good!

**Review by jlmitch5 — APPROVED** [review]
code looks great!

**Pull request merged**
