### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by kialam**
Upgrade our eslint library to support proper indentation of the React Fragment shorthand. See https://github.com/eslint/eslint/issues/12208

Remove eslint rule requiring spaces between curly braces in JSX - this is not recommended (https://airbnb.io/javascript/react/#spacing)

### CODE REVIEW

**Comment by brumik** [comment]
@kialam You should drop the last commit, it is faulty, this is why the linting fails in travis tests (and also makes incredible amount of changes in nearly all files)

**Comment by kialam** [comment]
The issue is not prettier - the linter is failing based on a `no-redeclare` rule.

**Comment by brumik** [comment]
Ah, okay, I see you removed the `spacing` rule. So we want to fix up the problems manually?

**Comment by kialam** [comment]
@brumik yes. Apologies for all the noise in this PR due to the re-formatting. This should be ready to be merged once approved (linter and tests are now passing)

**Review by jeanetteobr — APPROVED** [review]

**Comment by jeanetteobr** [comment]
LGTM!

**Pull request merged**
