### PR TITLE
Quickfix 2.0 - switch default false on job explorer page 

### PR DESCRIPTION
**Pull request by brumik**
#186 

Could not find the exact cause of the problem, but checking with type for true solved it. The values passed to the component are seem like always correct.

### CODE REVIEW

**Review by kialam — CHANGES_REQUESTED** [review]
This code forces the param to be false always, so that if you were to pass it from a different component (e.g. from say the bar chart), it would be false regardless.

**Comment by brumik** [comment]
It took me a while but you were right. The problem is that in the URL you cannot send boolean, so `true` or `false` after parsing the URL becomes `"true"` resp. `"false"`. I think we could maybe make the conversion in the `queryParams` component but after messing with it I could not get it to work. Or we can just convert all true and false to strings when used and in the toolbar set the `isChecked={ onlyRootWorkflows === 'true' }`

@kialam 

Also, it is good to go if you think so too.

**Comment by benthomasson** [comment]
@kialam @brumik what is the state of this fix?

**Comment by brumik** [comment]
It fixes the issue. What I wrote above is more of a consideration to make it more consistent in behavior or more bullet proof. 

So for me it could be merged and maybe do a follow-up pr if kia thinks so

**Comment by benthomasson** [comment]
OK thanks!

**Review by benthomasson — APPROVED** [review]

**Review by kialam — APPROVED** [review]
LGTM

**Pull request merged**
