### PR TITLE
[AA-1856] Remove alert banner

### PR DESCRIPTION
**Pull request by skochay330**
Removes delayed data banner from crc ui

Jira issue: https://issues.redhat.com/browse/AA-1856

### CODE REVIEW

**Comment by skochay330** [comment]
@dmzoneill Let me know when we can go ahead and merge this

**Comment by dmzoneill** [comment]
@skochay330 

I'm not getting a good feeling off all those dependency issues.
It might be worth pausing merges until @ZitaNemeckova or someone cleans up the dependancy noise.
If you really want to get the banner gone, converse with @h-kataria and determine whether to ignore and continue.

```14:18:14 npm ERR! Invalid: lock file's @redhat-cloud-services/rbac-client@1.2.8 does not satisfy @redhat-cloud-services/rbac-client@1.2.10```

**Comment by h-kataria** [comment]
@dmzoneill @skochay330 i think Zita had volunteered to look into those, but I don't think we have to wait on that to merge this PR as this one does not have any related changes. @dmzoneill we should merge this PR if data rollup task is in good shape.

**Review by dmzoneill — APPROVED** [review]

**Review by h-kataria — APPROVED** [review]

**Pull request merged**
