### PR TITLE
[AA-1511] Replace page headers

### PR DESCRIPTION
**Pull request by skochay330**
The `PageHeader` and `PageHeaderTitle` components from Red Hat cloud services have been replaced with the `PageHeader` component from the ansible-ui framework. For pages without a filter toolbar in the header, the only changes in the UI are very minor and consist of padding changes and a border on the bottom of the header section. For pages with a filter toolbar, the UI changes are as shown in the screenshots below. 

Jira issue: https://issues.redhat.com/browse/AA-1511 

Before: 
Screenshot 2023-02-27 at 11 46 36 AM

After: 
Screenshot 2023-02-27 at 11 45 21 AM

### CODE REVIEW

**Comment by h-kataria** [comment]
changes look good to me

**Review by h-kataria — APPROVED** [review]

**Comment by ZitaNemeckova** [comment]
Cypress failure may be partly related to the changes.

**Comment by skochay330** [comment]
@ZitaNemeckova I double checked the errors with @fullsushidev and we confirmed that we can ignore them for now. They are a result of cypress bugs that are being worked on.

**Review by daphnemaeve — APPROVED** [review]
Looks good to me!

**Pull request merged**
