### PR TITLE
Automation Calculator UXD Audit 

### PR DESCRIPTION
**Pull request by jeanetteobr**
This PR handles UXD Audit changes to the Automation Calculator.

### **#285 Use Popover instead of Tooltip in template details**

Verification:
Screen Shot 2020-10-08 at 5 11 16 PM

### **#286** UXD Audit Suggestions to Automation Calculator
- Add gray bottom border to card titles
- Remove toggle from top templates details card
- Bump up size of total savings number to improve visual hierarchy and add blue top border
- Combine editable cards on right side of page into one panel.

Verification:
Screen Shot 2020-10-08 at 5 11 04 PM

### CODE REVIEW

**Review by kialam — DISMISSED** [review]
The two columns need to maintain the same total height. Currently if you resize the browser the right column can get longer than the left one.

Current:
Screen Shot 2020-10-13 at 5 55 31 PM

Existing:
Screen Shot 2020-10-13 at 5 57 36 PM

**Comment by kialam** [comment]
Hmm, @jeanetteobr are you seeing this as well?
Screen Shot 2020-11-03 at 10 14 36 AM

**Comment by jeanetteobr** [comment]
@kialam Blast! I'm wondering if I set overflow to hidden on that section would be sufficient enough. 🤔

**Review by benthomasson — APPROVED** [review]

**Comment by appuk** [comment]
Everything looks good! 👍

**Pull request merged**
