### PR TITLE
Bump node to 20+, analytics ui version to 1.8.0

### PR DESCRIPTION
**Pull request by himdel**
Node 18 is EOL in early 2025, bumping to v20.

And changing the automation-analytics js package version to 1.8.0, so that we can tell if it was successfully deployed.

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
I cannot verify on stage because it's broken...
Screenshot 2024-12-03 at 12 42 57

**Comment by himdel** [comment]
@ZitaNemeckova Mea culpa, fixed now, https://github.com/RedHatInsights/tower-analytics-frontend/pull/1110/commits/c75349da160aa601b3c77e4009b38cba9ec79203 :) (introduced in #1101)

**Comment by himdel** [comment]
Merging to make sure the changes hold up on stage.

**Comment by ZitaNemeckova** [comment]
👍

**Pull request merged**
