### PR TITLE
Replace data-testid with data-cy

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
cc @fullsushidev

### CODE REVIEW

**Comment by fullsushidev** [comment]
thank you @ZitaNemeckova

**Comment by fullsushidev** [comment]
@ZitaNemeckova Could we maybe use only one id for tests in general? either jest or cypress?

**Comment by ZitaNemeckova** [comment]
@fullsushidev I'll have a look into removing `data-testid`.

**Comment by ZitaNemeckova** [comment]
@fullsushidev I replaced `data-testid`. Harpreet agreed that `data-cy` is better.

**Comment by fullsushidev** [comment]
@ZitaNemeckova @h-kataria Could we merge this PR?

**Pull request merged**
