### PR TITLE
[AA-1798] Fix redirect to job explorer from clusters and savings planner pages

### PR DESCRIPTION
**Pull request by skochay330**
This PR fixes redirects to the job explorer page from the clusters page and the savings planner details tab. 

Related to https://github.com/RedHatInsights/tower-analytics-frontend/pull/984 where the same thing was done for the redirect from automation calculator. 

Jira issue: https://issues.redhat.com/browse/AA-1798

### CODE REVIEW

**Comment by skochay330** [comment]
Ignore codecov failure, we are not able to use jest to check redirects as of right now.

**Review by daphnemaeve — APPROVED** [review]

**Pull request merged**
