### PR TITLE
[WIP] Use domain and y Tickvalues provided by backend

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Replaces #866 

Backend MR https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/568

### CODE REVIEW

**Comment by h-kataria** [comment]
@ZitaNemeckova see comments from Aparna below, can you please address them

https://ansible.slack.com/archives/D01SURL1318/p1664905226975619

https://ansible.slack.com/archives/D01SURL1318/p1664920729160999

need to fetch schema and hydrateSchema when a template is changed.

**Comment by AparnaKarve** [comment]
Other than the issue mentioned [above](https://github.com/RedHatInsights/tower-analytics-frontend/pull/867#issuecomment-1268108176), with the changes in this PR along with the backend changes, the scatter plots are looking much much better than before.

Notable improvements -
- Horizontal lines after regular intervals coming from the y-axis
- Y Ticks are more number-rounding-friendly (as in, in multiples of 2 or 5) . 
  For e.g. In Case3 (Before) there are values like `527` and `791`,  which are somewhat odd -- they have been replaced with an even `600` and `800` in Case3 (After)
- The zero line has been shifted up
-  The gray background is more pleasing to the eyes

------------------------------

Here are some Before's and After's -

### Case1 (Before)

before1

### Case1 (After)

after1



------------------------------

### Case2 (Before)
before2



### Case2 (After)


after2

------------------------------

### Case3 (Before)
before3




### Case3 (After)

after3

**Comment by h-kataria** [comment]
@trahman73 can you please review/approve the screenshots above

**Comment by ZitaNemeckova** [comment]
@trahman73 me and @AparnaKarve think it looks better with the background color. Maybe a little lighter grey. WDYT?

**Comment by trahman73** [comment]
@ZitaNemeckova I think PF will most likely ask us to change this to match theirs as the background color can cause potential  issues with their accessibility guidelines. If we still wanted to try a background color, we could try something lighter like #fafafa

**Comment by AparnaKarve** [comment]
Changed the background color to #fafafa

Screen Shot 2022-10-20 at 4 00 14 PM

**Comment by AparnaKarve** [comment]
@h-kataria @ZitaNemeckova While the code changes here work 85-90% of the times, I have noticed that there are times when the y-tick values of the new template do not always apply when a template is switched -- as in, the new template continues to show the y-tick values of the previous template. 
A page refresh fixes the chart with the new y-tick values for the template.

Wondering if this issue is easily fixable. If not, we can leave it as is.

**Comment by ZitaNemeckova** [comment]
@AparnaKarve Thanks for review. I cleaned the code and it seems to help with the issue you were seeing. Could you please re-review?

**Comment by ZitaNemeckova** [comment]
Waits on PF

**Comment by h-kataria** [comment]
closing in favor of https://github.com/RedHatInsights/tower-analytics-frontend/pull/878

**Pull request closed without merging**
