### PR TITLE
Misc UXD Audit Changes

### PR DESCRIPTION
**Pull request by jeanetteobr**
This PR handles two UXD audit changes:

**Change badges to numbers (#272)**
Current:
Screen Shot 2020-11-02 at 4 21 12 PM

Verification:
Screen Shot 2020-11-02 at 4 20 18 PM

**Remove Automation Analytics from Page Titles(#275)**
Current:
Screen Shot 2020-11-02 at 4 20 56 PM

Verification:
Screen Shot 2020-11-02 at 4 20 42 PM

### CODE REVIEW

**Review by brumik — APPROVED** [review]
LGTM

**Comment by benthomasson** [comment]
Does this address #317

**Comment by benthomasson** [comment]
@jeanetteobr Does this address #317?

**Comment by jeanetteobr** [comment]
@benthomasson Yes! The title will read as "Job Explorer" once this branch gets merged to devel.

**Review by benthomasson — APPROVED** [review]

**Pull request merged**
