### PR TITLE
Converting charts to functional components

### LINKED ISSUE #102: Refactor LineChart.js into Functional Component
Currently LineChart.js is a class based component. We would like to refactor this into a functional component that uses hooks. A good example of this is BaseChart.js in the src directory of the tower-analytics-frontend repo.

### LINKED ISSUE #103: Refactor PieChart.js into Functional Component
Currently PieChart.js is a class based component. We would like to refactor this into a functional component that uses hooks. A good example of this is BaseChart.js in the src directory of the tower-analytics-frontend repo.

### LINKED ISSUE #104: Refactor GroupedBarChart.js into Functional Component
Currently GroupedBarChart.js is a class based component. We would like to refactor this into a functional component that uses hooks. A good example of this is BaseChart.js in the src directory of the tower-analytics-frontend repo.

### PR DESCRIPTION
**Pull request by brumik**
Closes: #94 closes #102 closes #103 and closes #104

Converts the `BarChart`, `GruppedBarChart`, `LineChart`, `PieChart` to a functional component.
Coverts `BaseChart` to a functional component and fixes a console error where the `propTypes` were declared inside the component instead of after.

No UI changes as far as I tested it well.

### CODE REVIEW

**Comment by brumik** [comment]
Hm, okey, I didn't notice the flittering, will try to compare with the master. I'll look into this in Friday.

**Comment by brumik** [comment]
It should be good now, had a problem where you cannot store timeouts and intervals in hook states.

Should be good for re-review. Thanks @kialam

**Comment by brumik** [comment]
I managed to fix it but it is a bit hacky maybe? Used an extra counter as setTimeout has only the initial value of `useState` variable. The only way around is to create `useRef` and update it when changed, which is not a good pattern with functions. If you know a better solution I would be happy to hear otherwise I think this is good enough.

**Comment by brumik** [comment]
Still, applies? It worked for me. I force pushed the corrected version.

**Comment by jeanetteobr** [comment]
Hi @brumik Sorry for the confusion there! I had to re-request a review from me in order to request changes on this PR. Your workaround looks good to me and the app is working as expected. Great job!

**Pull request merged**
