### PR TITLE
[AA-660] Api calls error and loading handling - step 1/4

### PR DESCRIPTION
**Pull request by brumik**
@h-kataria @jlmitch5 @skochay330 

I would be happy if you would check if you like this format of API handling and to see if you can break it somehow or if it introduces some bugs. I think this is the first critical part, since I tried to make a component which can handle errors.

Followup if this is good
* Add in a followup PR the handling of RBAC errors too for the savings planner
* Review the PR from the previous step thoroughly - like this PR.
* Update in one big swoop all the components to this and to the RBAC template
* Sleep calmly knowing that we are handling loading and errors from API correctly trough generalized components :)

Hoping that with splitting up the refactor (can I call this a refactor?) into small pieces we can spot bugs faster and make reviews faster resulting in better product quality.

### CODE REVIEW

**Comment by jlmitch5** [comment]
Let's close this for now.  I think we've done a bit too much on refactoring things related to the api requests, and we need to let the code base settle with the query param changes that are going in and we can revisit.

**Comment by brumik** [comment]
This is the smallest "refactor" we had for a long time. It is rather a bugfix. I just added two components which can handle all the api errors and put a wrapper around components that uses them. 

If I remove the Job explorer page changes, can we get at least those two files in? It took a long time and Ladas to figure out what API error can we get and how to handle it for data and options endpoints.

**Comment by jlmitch5** [comment]
👍  that sounds good

**Comment by brumik** [comment]
@jlmitch5 @h-kataria I opened this PR in September to introduce a new more consistent and fail proof format of API handling on pages. In 9 month I rebased it once and I remember explaining and talking about it with John (who approved the motiv). I think at this point we could potentially throw away this initiative. The product is moving into less pages - more reports and what is in the codebase is still working just right, even if it is not the most consistent. 

If there is still interest, I am happy to spend some time with the team/on it too.

**Comment by h-kataria** [comment]
Assigned Jira task to @ZitaNemeckova for now, we will take a look at this at a later time. Closing this PR for now.

**Pull request closed without merging**
