### PR TITLE
Bump react chart builder library version

### PR DESCRIPTION
**Pull request by skochay330**
Updating react-json-chart builder library from `^1.10.2` to `^1.13.0`

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@skochay330 When you update existing dependency or install a new one  you should run `npm install` to make sure package-lock.json is updated as well.

**Comment by ZitaNemeckova** [comment]
@skochay330 I tried it and it seems to break when I run `npm start`. Please let me know if it happens to you too.

```
ERROR in /Users/zita/Desktop/AnsibleAnalytics/tower-analytics-frontend/node_modules/victory-core/lib/index.d.ts
15:29-40
[tsl] ERROR in /Users/zita/Desktop/AnsibleAnalytics/tower-analytics-frontend/node_modules/victory-core/lib/index.d.ts(15,30)
      TS1005: ',' expected.
ts-loader-default_e3b0c44298fc1c14
```

It seems to be a known issue https://github.com/FormidableLabs/victory/issues/2358

**Comment by skochay330** [comment]
@ZitaNemeckova After running `npm install` and restarting my local environment, I am seeing two errors: 
```
ERROR in ./node_modules/@patternfly/react-charts/dist/esm/components/ChartCursorContainer/ChartCursorContainer.js 7:0-66

Module not found: Error: Can't resolve 'victory-cursor-container' in '/Users/skochay330/Dev/tower-analytics-frontend/node_modules/@patternfly/react-charts/dist/esm/components/ChartCursorContainer'


ERROR in /Users/skochay330/Dev/tower-analytics-frontend/node_modules/victory-core/lib/index.d.ts 15:29-40

[tsl] ERROR in /Users/skochay330/Dev/tower-analytics-frontend/node_modules/victory-core/lib/index.d.ts(15,30)
      TS1005: ',' expected.
```

**Comment by ZitaNemeckova** [comment]
@jeanetteobr When you test it you should do just `npm ci && npm start`. You shouldn't need to do all the magic from my comment above.

**Comment by ZitaNemeckova** [comment]
I opended https://github.com/patternfly/patternfly-react/issues/7791 so we can remove `victory-cursor-container` once it's fixed.

**Review by jeanetteobr — APPROVED** [review]

**Pull request merged**
