### PR TITLE
Used data in meta['legend'] instead of items from API response

### PR DESCRIPTION
**Pull request by h-kataria**
UI changes to address changes in API response in https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/315

https://issues.redhat.com/browse/AA-958

@AparnaKarve please review

### CODE REVIEW

**Comment by h-kataria** [comment]
@skochay330 we will need the same change on the PDF side.

**Review by AparnaKarve — APPROVED** [review]
Looks good, thanks!

**Review by jlmitch5 — APPROVED** [review]
code looks great

**Pull request merged**
