### PR TITLE
[AA-1509] Update react dom router

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
TODO:

- [x] `<Redirect />` -> `<Navigate />`
 _Note: `import { useRedirect } from '../../QueryParams';` stays as it isn't related to this update._ 

- [x] no `<BrowserRouter>` (cloud specific)

- [x]  `<Switch>` -> `<Routes>`

- [x]  no `useHistory`

- [x] ` history.push(...)` -> `navigate(...)`

- [x] `history.listen(() -> ...)` -> ` useEffect(() => { ... }, [location]);`

- [x] Fix Reports routing
   
   - Fix Card Title to redirect to Report Detail page now it takes onClick over the Link 

- [x] Fix Savings Plannner
- [x] Move all `<Route>` to main file (SavingsPlanner, Reports, ...)
- [x] Fix tests
- [x] Fix Cypress tests 

Known issue:

-  When trying to Add a new Saving plan it flickers and never shows the page. This is not related to this PR. Tracked by https://issues.redhat.com/browse/AA-1519
- Tests failing
- In Saving planner detail page tabs not correctly highlighted - Fixed

https://reactrouter.com/en/main/upgrading/v5

### CODE REVIEW

**Review by skochay330 — COMMENTED** [review]
Great work! Here are some bugs I found in the UI:

- Links to reports from organization statistics page are broken

- When a filter is applied in a report preview and a new report is selected, page breaks

- Clickable linking is broken in most used modules report

- Clicking on an ID/name in job explorer loads for a while then times out

**Comment by ZitaNemeckova** [comment]
- Links to reports from organization statistics page are broken -> Fixed

- When a filter is applied in a report preview and a new report is selected, page breaks -> Not related to this PR

- Clickable linking is broken in most used modules report -> TODO

- Clicking on an ID/name in job explorer loads for a while then times out -> TODO

**Comment by ZitaNemeckova** [comment]
- [ ] “View all jobs” link is broken in pop-up when you click on a template link on the clusters page

- [ ] Clickable linking is broken in most used modules report

- [ ] Page breaks when a template link is selected on a savings planner card

- [ ] Template links do not work in savings planner details view

- [ ] Template links are broken in automation calculator table

**Review by skochay330 — APPROVED** [review]
Everything seems to be working as expected. Thank you for your patience in addressing all of the bugs!

**Comment by ZitaNemeckova** [comment]
@skochay330 Thank you for amazing work on reviews!

**Pull request merged**
