### PR TITLE
UI release

### PR DESCRIPTION
**Pull request by h-kataria**

### CODE REVIEW

**Review by skochay330 — APPROVED** [review]

**Review by fullsushidev — CHANGES_REQUESTED** [review]
It seems the package-lock file needs to be updated. That's why the test pipelines are not working!

**Comment by h-kataria** [comment]
@fullsushidev we do not update package-lock file with UI release PR

**Comment by ZitaNemeckova** [comment]
@h-kataria Ingrid is right. If I run `npm ci` locally on this PR it ends in failure.

**Pull request merged**
