### PR TITLE
Move filter toolbar to the top title section per UXD's suggestion.

### PR DESCRIPTION
**Pull request by kialam**
After changes:
Screen Shot 2021-02-11 at 10 36 12 AM
Screen Shot 2021-02-11 at 10 36 06 AM

### CODE REVIEW

**Comment by brumik** [comment]
If we are moving it should not be moved on all pages? (Or is this PR still WIP?)

**Comment by kialam** [comment]
So it needs to be moved on the Orgs and Automation calculator page because the filters are top level. For the Job Explorer it only applies to the table so it does not need to be moved. Same goes for the Notifications page.

**Comment by brumik** [comment]
It seems a little strange for me, since we have nothing else on these pages, so even when the filter is applied only on the table, it is basically affecting the whole page. But I can accept that later it will be changing maybe and more content will be added to the pages which use different filters maybe.

**Review by brumik — APPROVED** [review]
LGTM

**Pull request merged**
